apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/leejiho1996/catalog-service/k8s?ref=main

#  patch 파일의 kind 와 metadata.name 이
#  base 리소스의 kind 와 metadata.name 과 일치하면
#  -> 그 리소스에 patch 내용이 merge(덮어쓰기/추가)
patchesStrategicMerge:
- patch-env.yml
- patch-volume.yml
- patch-resources.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/leejiho1996/catalog-service
  newTag: 85b17af914137868ea98a68277931897110b3750

replicas:
- count: 2
  name: catalog-service
