version: "3.8"
services:

  # Applications

  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001 # 디버깅을 위한 포트
    environment:
      - BPL_JVM_THREAD_COUNT=50 # 메모리 계산을 위한 스레드 수를 설정하는 패키토 빌드팩 환경 변수 
      - BPL_DEBUG_ENABLED=true # 디버그 연결을 위해 JVM 설정 활성화 (패키토 빌드팩에 의해 제공)
      - BPL_DEBUG_PORT=8001 # 디버깅을 위한 포트
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
  
  polar-postgres:
    image: "postgres:14.12"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      # - POSTGRES_DB=polardb_catalog
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql # 컨테이너 내부 경로에 init.sql 파일 마운트 후 실행